# Generated by Django 2.2.10 on 2020-03-25 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('summary', models.CharField(max_length=254)),
                ('height_field', models.SmallIntegerField(verbose_name='Height Field')),
                ('width_field', models.SmallIntegerField(verbose_name='Width Field')),
                ('picture', models.ImageField(height_field=models.SmallIntegerField(verbose_name='Height Field'), help_text='picture size: 525x350', max_length=254, upload_to='site/blog', verbose_name='Picture', width_field=models.SmallIntegerField(verbose_name='Width Field'))),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to='news.NewsCategory', verbose_name='NewsCategory')),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('posts', models.ManyToManyField(to='news.NewsPost', verbose_name='NewsPosts')),
            ],
            options={
                'verbose_name': 'News Tag',
                'verbose_name_plural': 'News Tags',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_comments', to=settings.AUTH_USER_MODEL, verbose_name='By user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='news.NewsPost', verbose_name='NewsPost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_comment', to='news.NewsComment', verbose_name='reply')),
            ],
            options={
                'verbose_name': 'News Comment',
                'verbose_name_plural': 'News Comments',
            },
        ),
    ]
