# Generated by Django 2.2.10 on 2020-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstag',
            name='posts',
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(to='news.NewsTag', verbose_name='News Tags'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='height_field',
            field=models.SmallIntegerField(editable=False, verbose_name='Height Field'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='picture',
            field=models.ImageField(height_field='height_field', help_text='picture size must be: 525x350', max_length=254, upload_to='site/blog', verbose_name='Picture', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='width_field',
            field=models.SmallIntegerField(editable=False, verbose_name='Width Field'),
        ),
    ]
