# Generated by Django 2.2.10 on 2020-04-06 05:35

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200325_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='alternate_picture',
            field=models.CharField(default='lorem', max_length=120, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='lorem', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='source',
            field=models.URLField(default='http://localhost:8000/admin/news/newspost/add/', verbose_name='Web Link Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to='news.NewsCategory', verbose_name='News Category'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='summary',
            field=ckeditor.fields.RichTextField(max_length=254),
        ),
    ]
