# Generated by Django 2.2.10 on 2020-04-06 05:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200405_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='alternate_picture',
            field=models.CharField(help_text='use for SEO of picture', max_length=120, verbose_name='Alternate Picture'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Web Link Source'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='summary',
            field=ckeditor.fields.RichTextField(max_length=400),
        ),
    ]
