# Generated by Django 2.2.10 on 2020-04-11 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200405_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
