# Generated by Django 2.2.10 on 2020-05-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200411_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ('-created',), 'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
    ]
