# Generated by Django 2.2.10 on 2020-04-05 15:49

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('from_where', models.CharField(choices=[('google search', 'Google Search'), ('pinterest', 'Telegram'), ('instagram', 'Instagram'), ('from people', 'from people')], max_length=20, verbose_name='from where')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='Owner Name')),
                ('name', models.CharField(max_length=200, verbose_name='Website Name')),
                ('domain', models.URLField(verbose_name='Domain')),
                ('phone_number', models.CharField(help_text='+98912...', max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=254, verbose_name='Address')),
                ('about_us', ckeditor.fields.RichTextField(verbose_name='About us')),
                ('service_desc', ckeditor.fields.RichTextField(verbose_name='Our Services')),
                ('logo', models.FileField(upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('width_field_icon', models.PositiveIntegerField(editable=False, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(30)], verbose_name='Width Field')),
                ('height_field_icon', models.PositiveIntegerField(editable=False, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(30)], verbose_name='Height Field')),
                ('icon', models.FileField(help_text='valid size is 30x30', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('insta', models.URLField(verbose_name='Instagram')),
                ('linkedin', models.URLField(verbose_name='Linkedin')),
                ('mail', models.EmailField(max_length=200, verbose_name='Mail')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
