# Generated by Django 2.2.10 on 2020-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Name')),
                ('national_code', models.CharField(max_length=100, verbose_name='National Code')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('investment', models.CharField(choices=[('under 100 milion', 'زیر 100 میلیون تومان'), ('between 100 to 500 milion', 'از 100 تا 500 میلیون تومان'), ('between 500 milion to 1 miliard', 'از 500 میلیون تا یک میلیارد تومان'), ('between 1 to 5 miliard', 'از 1 تا 5 میلیارد تومان'), ('between 5 to 10 miliard', 'از 5 تا 10 میلیارد توامن'), ('above 10 miliard', 'بیش از 10 میلیارد تومان')], max_length=50, verbose_name='Investment')),
                ('familiarity', models.CharField(choices=[('low', 'کم'), ('Moderate', 'متوسط'), ('well', 'خوب'), ('high', 'عالی')], max_length=50, verbose_name='Familiarity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created',),
            },
        ),
    ]
