# Generated by Django 2.2.10 on 2020-04-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_openaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaccount',
            options={'ordering': ('-created',), 'verbose_name': 'Account', 'verbose_name_plural': 'Accountss'},
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
    ]
