# Generated by Django 2.2.10 on 2020-03-25 07:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialpost',
            options={'ordering': ('-created',), 'verbose_name': 'Tutorial Post', 'verbose_name_plural': 'Tutorial Posts'},
        ),
        migrations.AddField(
            model_name='tutorialpost',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='tutorialpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tutorialpost',
            name='title',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Title'),
        ),
        migrations.AlterIndexTogether(
            name='tutorialpost',
            index_together={('id', 'slug')},
        ),
    ]
