# Generated by Django 2.2.10 on 2020-03-25 08:54

import django.core.validators
from django.db import migrations, models
import painless.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200325_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialbadge',
            name='slug',
            field=models.SlugField(editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tutorialpicture',
            name='picture',
            field=models.ImageField(height_field='height_field', help_text='picture size must be: 525x350', max_length=254, upload_to=painless.upload_to.tutorial_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Picture', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='tutorialpost',
            name='slug',
            field=models.SlugField(editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tutorialstatus',
            name='slug',
            field=models.SlugField(editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tutorialtag',
            name='slug',
            field=models.SlugField(editable=False, max_length=140, verbose_name='Slug'),
        ),
    ]
