# Generated by Django 2.2.10 on 2020-05-05 10:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('abbrivation', models.CharField(max_length=120, verbose_name='Abbrivation')),
                ('date', models.DateField(verbose_name='Date')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'PrimaryMarket',
                'verbose_name_plural': 'PrimaryMarkets',
                'ordering': ('-created',),
            },
        ),
    ]
