# Generated by Django 2.2.10 on 2020-05-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200503_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(to='shop.ProductPicture', verbose_name='Product Picture'),
        ),
    ]
