# Generated by Django 2.2.10 on 2020-03-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Analyze Category',
                'verbose_name_plural': 'Analyze Categories',
            },
        ),
        migrations.CreateModel(
            name='AnalyzePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('summary', models.CharField(max_length=254)),
                ('height_field', models.SmallIntegerField(verbose_name='Height Field')),
                ('width_field', models.SmallIntegerField(verbose_name='Width Field')),
                ('picture', models.ImageField(height_field=models.SmallIntegerField(verbose_name='Height Field'), help_text='picture size: 525x350', max_length=254, upload_to='site/blog', verbose_name='Picture', width_field=models.SmallIntegerField(verbose_name='Width Field'))),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ana_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ana_posts', to='analysis.AnalyzeCategory', verbose_name='AnalyzeCategory')),
            ],
            options={
                'verbose_name': 'Analyze Post',
                'verbose_name_plural': 'Analyze Posts',
            },
        ),
        migrations.CreateModel(
            name='AnalyzeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('posts', models.ManyToManyField(to='analysis.AnalyzePost', verbose_name='AnalyzePosts')),
            ],
            options={
                'verbose_name': 'Analyze Tag',
                'verbose_name_plural': 'Analyze Tags',
            },
        ),
        migrations.CreateModel(
            name='AnalyzeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ana_comments', to=settings.AUTH_USER_MODEL, verbose_name='By user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ana_comments', to='analysis.AnalyzePost', verbose_name='AnalyzePost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ana_comment', to='analysis.AnalyzeComment', verbose_name='reply')),
            ],
            options={
                'verbose_name': 'Analyze Comment',
                'verbose_name_plural': 'Analyze Comments',
            },
        ),
    ]
