# Generated by Django 2.2.10 on 2020-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200325_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzepost',
            name='picture',
            field=models.ImageField(height_field='height_field', help_text='picture size: 525x350', max_length=254, upload_to='site/blog', verbose_name='Picture', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='analyzepost',
            name='tags',
            field=models.ManyToManyField(to='analysis.AnalyzeTag', verbose_name='Analyze Tags'),
        ),
    ]
