# Generated by Django 2.2.10 on 2020-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200325_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzepost',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=140, verbose_name='Slug'),
        ),
    ]
