# Generated by Django 2.2.10 on 2020-03-25 10:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200325_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzepost',
            options={'ordering': ('-created',), 'verbose_name': 'Analyze Post', 'verbose_name_plural': 'Analyze Posts'},
        ),
        migrations.AddField(
            model_name='analyzepost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='lorem ipsum', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyzepost',
            name='title',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Title'),
        ),
        migrations.AlterIndexTogether(
            name='analyzepost',
            index_together={('id', 'slug')},
        ),
    ]
