# Generated by Django 2.2.10 on 2020-05-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200325_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzepost',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Important post'),
        ),
        migrations.AddField(
            model_name='analyzepost',
            name='is_shown',
            field=models.BooleanField(default=False, verbose_name='Show this post'),
        ),
    ]
